server {
    listen 80;
    
    location / {
        root /app;
        index index.html;
        try_files $uri $uri/ /index.html;
        error_page 404 /404.html;
    }

    location = /style.css {
        root /app;
        add_header Content-Type "text/css; charset=utf-8";
        try_files $uri =404;
    }

    location = /404.css {
        root /app;
        add_header Content-Type "text/css; charset=utf-8";
        try_files $uri =404;
    }

    location /styles/ {
        root /app;
        add_header Content-Type "text/css; charset=utf-8";
        try_files $uri =404;
    }

    location /scripts/ {
        root /app;
        try_files $uri =404;
    }
} 