server {
    listen 80;
    
    location / {
        root /app;
        index index.html;
        try_files $uri $uri/ /index.html;
        error_page 404 /404.html;
    }

    location /style.css {
        alias /app/style.css;
        add_header Content-Type "text/css; charset=utf-8";
    }

    location /styles/ {
        alias /app/styles/;
        add_header Content-Type "text/css; charset=utf-8";
    }

    location /scripts/ {
        alias /app/scripts/;
    }
} 